spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/mazebuddy_local
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Application is running properly right now local!