spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/studentmanagement-prod
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Application is running properly right now prod!

management:
  endpoints:
    web:
      exposure:
        #        include: "*"
        include: "features"
        exclude: "env,beans"